# Generated by Django 5.2.3 on 2025-08-27 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('key', models.CharField(max_length=255)),
                ('key_description', models.TextField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Provider Credential',
                'verbose_name_plural': 'Provider Credentials',
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(choices=[('paylov', 'Paylov'), ('payme', 'Payme'), ('click', 'Click')], max_length=255, verbose_name='Name')),
                ('key', models.CharField(max_length=255, verbose_name='Key')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=10, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Canceled at')),
                ('remote_id', models.CharField(blank=True, max_length=512, null=True, verbose_name='Remote id')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('extra', models.JSONField(blank=True, null=True, verbose_name='Extra data')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('card_token', models.CharField(max_length=255, verbose_name='Card Token')),
                ('cardholder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cardholder Name')),
                ('last_four_digits', models.CharField(blank=True, max_length=4, null=True, verbose_name='Last Four Digits')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand')),
                ('expire_month', models.CharField(max_length=2, verbose_name='Expire Month')),
                ('expire_year', models.CharField(max_length=4, verbose_name='Expire Year')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Is confirmed')),
            ],
            options={
                'verbose_name': 'User Card',
                'verbose_name_plural': 'User Cards',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', verbose_name='Status')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
